FROM ubuntu 





RUN apt-get update
RUN apt-get -y --force-yes install iproute2
RUN apt-get -y --force-yes install iptables
RUN apt-get -y --force-yes install iputils-ping
RUN apt-get -y --force-yes install tcpdump
RUN apt-get -y --force-yes install iperf

